dau:
  mcp:
    axis: "1 0.1 0.1"
    pos: "0.05 -0.21 -0.22"
    range: "-4 4"
  mcp2:
    axis: "0 1 0.1"
    pos: "0.05 -0.21 -0.22"
    range: "-4 4"
  pip:
    axis: "0 -1 -0.1"
    pos: "0.08 -0.22 -0.18"
    range: "-4 4"
  dip:
    axis: "-0 -1 -0.1"
    pos: "0.08 -0.22 -0.15"
    range: "-4 4"

zf:
  mcp:
    axis: "1 0.1 0.1"
    pos: "0.05 -0.17 -0.17"
    range: "-4 4"
  pip:
    axis: "1 0.1 0.1"
    pos: "0.05 -0.195 -0.13"
    range: "-4 4"
  dip:
    axis: "1 0.2 0.1"
    pos: "0.05 -0.22 -0.12"
    range: "-4 4"
